version: "0.5"

processes:
  dbos-go-starter:
    log_location: "logs/log_file.{PC_REPLICA_NUM}.log"
    command: >
      go run main.go -port 809$${PC_REPLICA_NUM} -executor-id $${PC_PROC_NAME}$${PC_REPLICA_NUM}
    replicas: 2
    depends_on:
      postgresql:
        condition: process_healthy
    log_configuration:
      disable_json: true # output as plain text. The default is false
      no_metadata: false # log process name and replica number
      add_timestamp: true # add timestamp to the logger. Default is false
      no_color: true # disable ANSII colors in the logger. Default is false
      flush_each_line: true # disable buffering and flush each line to the log file. Default is false

  haproxy:
    log_location: "logs/haproxy.log"
    command: >
      haproxy -f etc/haproxy.cfg
    replicas: 1
    # depends_on:
    #   dbos-go-starter:
    #     condition: process_started
    log_configuration:
      disable_json: true # output as plain text. The default is false
      no_metadata: false # log process name and replica number
      add_timestamp: true # add timestamp to the logger. Default is false
      no_color: true # disable ANSII colors in the logger. Default is false
      flush_each_line: true # disable buffering and flush each line to the log file. Default is false
