# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

dotenv:
  - .env

vars:
  GREETING: Hello, world!

tasks:
  default:
    desc: Print help
    cmds:
      - task -l
    silent: true

  run:
    desc: Run the application interactively
    cmds:
      - devbox services up

  workflow:*:
    desc: Workflow tasks - one of cancel, fork, get, list, resume, steps
    cmds:
      - go tool dbos workflow '{{index .MATCH 0}}' '{{.CLI_ARGS}}'

  dbinit:
    desc: Initialize the database
    cmds:
      - initdb
      - devbox services start postgresql
      - createdb dbos_toolbox_go
