# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

dotenv:
  - .env

vars:
  GREETING: Hello, world!

tasks:
  default:
    desc: Print help
    cmds:
      - task -l
    silent: true

  db:*:
    desc: Database tasks - one of start, stop
    cmds:
      - go tool dbos postgres '{{index .MATCH 0}}'

  run:
    desc: Run the application
    cmds:
      - go run main.go

  workflow:*:
    desc: Workflow tasks - one of cancel, fork, get, list, resume, steps
    cmds:
      - go tool dbos workflow '{{index .MATCH 0}}'
